"""move regeneration check fields to users with current plan id

Revision ID: 03dea5969b58
Revises: 08f5764c66b2
Create Date: 2026-09-06 15:14:17.323540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '03dea5969b58'
down_revision: Union[str, Sequence[str], None] = '08f5764c66b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_workout_plans', 'is_regeneration_required')
    op.drop_column('user_workout_plans', 'last_regeneration_check')
    op.add_column('users', sa.Column('current_plan_id', sa.Uuid(), nullable=True))
    op.add_column('users', sa.Column('is_regeneration_required', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('users', sa.Column('last_regeneration_check', sa.DateTime(), nullable=True))
    op.create_foreign_key(op.f('fk_users_current_plan_id_user_workout_plans'), 'users', 'user_workout_plans', ['current_plan_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###

    # Backfill current_plan_id from each user's most recently created plan, so
    # existing users don't lose their plan pointer in this restructuring.
    op.execute("""
        UPDATE users
        SET current_plan_id = latest.id
        FROM (
            SELECT DISTINCT ON (user_id) id, user_id
            FROM user_workout_plans
            ORDER BY user_id, created_at DESC
        ) AS latest
        WHERE users.id = latest.user_id
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_users_current_plan_id_user_workout_plans'), 'users', type_='foreignkey')
    op.drop_column('users', 'last_regeneration_check')
    op.drop_column('users', 'is_regeneration_required')
    op.drop_column('users', 'current_plan_id')
    op.add_column('user_workout_plans', sa.Column('last_regeneration_check', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('user_workout_plans', sa.Column('is_regeneration_required', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
