"""added isRegenerationRequiredCheck

Revision ID: 08f5764c66b2
Revises: 8632d2a6c92f
Create Date: 2026-09-06 14:56:45.451406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08f5764c66b2'
down_revision: Union[str, Sequence[str], None] = '8632d2a6c92f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_workout_plans', sa.Column('is_regeneration_required', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('user_workout_plans', sa.Column('last_regeneration_check', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_workout_plans', 'last_regeneration_check')
    op.drop_column('user_workout_plans', 'is_regeneration_required')
    # ### end Alembic commands ###
