"""added user_subscriptions

Revision ID: 16c85b57bc14
Revises: 1727bffa52ab
Create Date: 2026-08-13 01:26:43.635082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '16c85b57bc14'
down_revision: Union[str, Sequence[str], None] = '1727bffa52ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('MALE', 'FEMALE', 'OTHER', name='usersex').create(op.get_bind())
    sa.Enum('ACTIVE', 'CANCELLED', 'EXPIRED', 'PAUSED', name='subscriptionstatus').create(op.get_bind())
    sa.Enum('MONTHLY', 'QUARTERLY', 'YEARLY', 'WEEKLY', 'LIFETIME', name='subscriptionplanfrequency').create(op.get_bind())
    op.create_table('subscription_plans',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('frequency', postgresql.ENUM('MONTHLY', 'QUARTERLY', 'YEARLY', 'WEEKLY', 'LIFETIME', name='subscriptionplanfrequency', create_type=False), nullable=False),
    sa.Column('no_of_users', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subscription_plans'))
    )
    op.create_table('user_subscriptions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('subscription_plan_id', sa.Uuid(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('status', postgresql.ENUM('ACTIVE', 'CANCELLED', 'EXPIRED', 'PAUSED', name='subscriptionstatus', create_type=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['subscription_plan_id'], ['subscription_plans.id'], name=op.f('fk_user_subscriptions_subscription_plan_id_subscription_plans')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_subscriptions_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_subscriptions'))
    )
    op.create_index(op.f('ix_user_subscriptions_subscription_plan_id'), 'user_subscriptions', ['subscription_plan_id'], unique=False)
    op.create_index(op.f('ix_user_subscriptions_user_id'), 'user_subscriptions', ['user_id'], unique=False)
    op.alter_column('users', 'sex',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('MALE', 'FEMALE', 'OTHER', name='usersex'),
               existing_nullable=True,
               postgresql_using='UPPER(sex)::usersex')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'sex',
               existing_type=sa.Enum('MALE', 'FEMALE', 'OTHER', name='usersex'),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_index(op.f('ix_user_subscriptions_user_id'), table_name='user_subscriptions')
    op.drop_index(op.f('ix_user_subscriptions_subscription_plan_id'), table_name='user_subscriptions')
    op.drop_table('user_subscriptions')
    op.drop_table('subscription_plans')
    sa.Enum('MONTHLY', 'QUARTERLY', 'YEARLY', 'WEEKLY', 'LIFETIME', name='subscriptionplanfrequency').drop(op.get_bind())
    sa.Enum('ACTIVE', 'CANCELLED', 'EXPIRED', 'PAUSED', name='subscriptionstatus').drop(op.get_bind())
    sa.Enum('MALE', 'FEMALE', 'OTHER', name='usersex').drop(op.get_bind())
    # ### end Alembic commands ###
