"""updated gym table

Revision ID: 1727bffa52ab
Revises: 1133c45b68d3
Create Date: 2026-07-28 21:57:44.375063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1727bffa52ab'
down_revision: Union[str, Sequence[str], None] = '1133c45b68d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gyms', 'contact_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gyms', sa.Column('contact_number', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
