"""GoalQuestion category column name change

Revision ID: 18fb44347735
Revises: 1ec0ff055dc7
Create Date: 2026-07-23 01:33:22.137842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18fb44347735'
down_revision: Union[str, Sequence[str], None] = '1ec0ff055dc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal_questions', sa.Column('category_id', sa.Uuid(), nullable=True))
    op.drop_index(op.f('ix_goal_questions_category'), table_name='goal_questions')
    op.create_index(op.f('ix_goal_questions_category_id'), 'goal_questions', ['category_id'], unique=False)
    op.drop_constraint(op.f('fk_goal_questions_category_categories'), 'goal_questions', type_='foreignkey')
    op.create_foreign_key(op.f('fk_goal_questions_category_id_categories'), 'goal_questions', 'categories', ['category_id'], ['id'], ondelete='SET NULL')
    op.drop_column('goal_questions', 'category')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal_questions', sa.Column('category', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('fk_goal_questions_category_id_categories'), 'goal_questions', type_='foreignkey')
    op.create_foreign_key(op.f('fk_goal_questions_category_categories'), 'goal_questions', 'categories', ['category'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_goal_questions_category_id'), table_name='goal_questions')
    op.create_index(op.f('ix_goal_questions_category'), 'goal_questions', ['category'], unique=False)
    op.drop_column('goal_questions', 'category_id')
    # ### end Alembic commands ###
