"""gym owner user relationship

Revision ID: 25f8c3d9cabb
Revises: 66b5841b4e32
Create Date: 2026-07-28 21:34:24.818795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25f8c3d9cabb'
down_revision: Union[str, Sequence[str], None] = '66b5841b4e32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gyms', sa.Column('owner_user_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_gyms_owner_user_id'), 'gyms', ['owner_user_id'], unique=False)
    op.create_foreign_key(op.f('fk_gyms_owner_user_id_users'), 'gyms', 'users', ['owner_user_id'], ['id'], ondelete='SET NULL')
    op.drop_column('gyms', 'owner_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gyms', sa.Column('owner_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('fk_gyms_owner_user_id_users'), 'gyms', type_='foreignkey')
    op.drop_index(op.f('ix_gyms_owner_user_id'), table_name='gyms')
    op.drop_column('gyms', 'owner_user_id')
    # ### end Alembic commands ###
