"""updated excercise

Revision ID: 66b5841b4e32
Revises: 18fb44347735
Create Date: 2026-07-24 01:10:37.999774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '66b5841b4e32'
down_revision: Union[str, Sequence[str], None] = '18fb44347735'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('BEGINNER', 'INTERMEDIATE', 'ADVANCED', name='level').create(op.get_bind())
    op.add_column('exercises', sa.Column('excercise_level', postgresql.ENUM('BEGINNER', 'INTERMEDIATE', 'ADVANCED', name='level', create_type=False), nullable=False))
    op.drop_column('exercises', 'video_provider')
    op.drop_column('exercises', 'video_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises', sa.Column('video_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('exercises', sa.Column('video_provider', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('exercises', 'excercise_level')
    sa.Enum('BEGINNER', 'INTERMEDIATE', 'ADVANCED', name='level').drop(op.get_bind())
    # ### end Alembic commands ###
