"""expand diet type enum and add body measurement fields

Revision ID: 8518bab3b441
Revises: 9c92db1d8ae2
Create Date: 2026-07-15 16:38:38.477435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference
from alembic_utils.pg_enum import PGEnum

# revision identifiers, used by Alembic.
revision: str = '8518bab3b441'
down_revision: Union[str, Sequence[str], None] = '9c92db1d8ae2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('body_measurements', sa.Column('neck_cm', sa.Float(), nullable=True))
    op.add_column('body_measurements', sa.Column('body_fat_percent', sa.Float(), nullable=True))
    op.sync_enum_values(
        enum_schema='public',
        enum_name='diettype',
        new_values=['VEGETARIAN', 'EGGETARIAN', 'NON_VEGETARIAN', 'VEGAN', 'PESCATARIAN', 'KETO', 'LOW_CARB', 'MEDITERRANEAN', 'OTHER'],
        affected_columns=[TableReference(table_schema='public', table_name='users', column_name='diet_type')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='diettype',
        new_values=['VEGETARIAN', 'EGGETARIAN', 'NON_VEGETARIAN'],
        affected_columns=[TableReference(table_schema='public', table_name='users', column_name='diet_type')],
        enum_values_to_rename=[],
    )
    op.drop_column('body_measurements', 'body_fat_percent')
    op.drop_column('body_measurements', 'neck_cm')
    # ### end Alembic commands ###
