"""add user attendance table

Revision ID: 8632d2a6c92f
Revises: 3b693a03b642
Create Date: 2026-09-04 00:41:22.166813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8632d2a6c92f'
down_revision: Union[str, Sequence[str], None] = '3b693a03b642'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_attendance',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('attendance_date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_attendance_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_attendance'))
    )
    op.create_index(op.f('ix_user_attendance_attendance_date'), 'user_attendance', ['attendance_date'], unique=False)
    op.create_index(op.f('ix_user_attendance_user_id'), 'user_attendance', ['user_id'], unique=False)
    # Existing workout_logs rows predate attendance tracking and have no
    # attendance record to backfill against, so they're cleared before the
    # column becomes NOT NULL. child rows (workout_log_exercises/_sets)
    # cascade-delete with them.
    op.execute('DELETE FROM workout_logs')
    op.add_column('workout_logs', sa.Column('attendance_id', sa.Uuid(), nullable=False))
    op.drop_index(op.f('ix_workout_logs_workout_date'), table_name='workout_logs')
    op.create_index(op.f('ix_workout_logs_attendance_id'), 'workout_logs', ['attendance_id'], unique=False)
    op.create_foreign_key(op.f('fk_workout_logs_attendance_id_user_attendance'), 'workout_logs', 'user_attendance', ['attendance_id'], ['id'], ondelete='CASCADE')
    op.drop_column('workout_logs', 'workout_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout_logs', sa.Column('workout_date', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('fk_workout_logs_attendance_id_user_attendance'), 'workout_logs', type_='foreignkey')
    op.drop_index(op.f('ix_workout_logs_attendance_id'), table_name='workout_logs')
    op.create_index(op.f('ix_workout_logs_workout_date'), 'workout_logs', ['workout_date'], unique=False)
    op.drop_column('workout_logs', 'attendance_id')
    op.drop_index(op.f('ix_user_attendance_user_id'), table_name='user_attendance')
    op.drop_index(op.f('ix_user_attendance_attendance_date'), table_name='user_attendance')
    op.drop_table('user_attendance')
    # ### end Alembic commands ###
