"""created table

Revision ID: 9c92db1d8ae2
Revises: 
Create Date: 2026-07-12 19:22:05.842856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9c92db1d8ae2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_providers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_providers'))
    )
    op.create_table('equipments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_equipments'))
    )
    op.create_table('goal_questions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('question', sa.String(), nullable=False),
    sa.Column('question_type', postgresql.ENUM('CHECKBOX', 'RADIO', 'TEXT', name='question_type', create_type=False), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('category', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_goal_questions'))
    )
    op.create_table('gyms',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('contact_number', sa.String(), nullable=True),
    sa.Column('owner_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gyms'))
    )
    op.create_table('muscles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_muscles'))
    )
    op.create_table('roles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('name', name=op.f('uq_roles_name'))
    )
    op.create_table('ai_models',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('ai_provider_id', sa.Uuid(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ai_provider_id'], ['ai_providers.id'], name=op.f('fk_ai_models_ai_provider_id_ai_providers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_models'))
    )
    op.create_index(op.f('ix_ai_models_ai_provider_id'), 'ai_models', ['ai_provider_id'], unique=False)
    op.create_table('goal_question_options',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('question_id', sa.Uuid(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['goal_questions.id'], name=op.f('fk_goal_question_options_question_id_goal_questions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_goal_question_options'))
    )
    op.create_index(op.f('ix_goal_question_options_question_id'), 'goal_question_options', ['question_id'], unique=False)
    op.create_table('gym_equipments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('gym_id', sa.Uuid(), nullable=False),
    sa.Column('equipment_id', sa.Uuid(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipments.id'], name=op.f('fk_gym_equipments_equipment_id_equipments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['gym_id'], ['gyms.id'], name=op.f('fk_gym_equipments_gym_id_gyms'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gym_equipments'))
    )
    op.create_index(op.f('ix_gym_equipments_equipment_id'), 'gym_equipments', ['equipment_id'], unique=False)
    op.create_index(op.f('ix_gym_equipments_gym_id'), 'gym_equipments', ['gym_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('mobile_no', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('diet_type', postgresql.ENUM('VEGETARIAN', 'EGGETARIAN', 'NON_VEGETARIAN', name='diettype', create_type=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_users_role_id_roles')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email')),
    sa.UniqueConstraint('mobile_no', name=op.f('uq_users_mobile_no'))
    )
    op.create_index(op.f('ix_users_role_id'), 'users', ['role_id'], unique=False)
    op.create_table('body_measurements',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('trainer_id', sa.Uuid(), nullable=True),
    sa.Column('gym_id', sa.Uuid(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('height_cm', sa.Float(), nullable=True),
    sa.Column('chest_cm', sa.Float(), nullable=True),
    sa.Column('waist_cm', sa.Float(), nullable=True),
    sa.Column('hips_cm', sa.Float(), nullable=True),
    sa.Column('left_arm_cm', sa.Float(), nullable=True),
    sa.Column('right_arm_cm', sa.Float(), nullable=True),
    sa.Column('left_thigh_cm', sa.Float(), nullable=True),
    sa.Column('right_thigh_cm', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['gym_id'], ['gyms.id'], name=op.f('fk_body_measurements_gym_id_gyms'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trainer_id'], ['users.id'], name=op.f('fk_body_measurements_trainer_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_body_measurements_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_body_measurements'))
    )
    op.create_index(op.f('ix_body_measurements_gym_id'), 'body_measurements', ['gym_id'], unique=False)
    op.create_index(op.f('ix_body_measurements_trainer_id'), 'body_measurements', ['trainer_id'], unique=False)
    op.create_index(op.f('ix_body_measurements_user_id'), 'body_measurements', ['user_id'], unique=False)
    op.create_table('exercises',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('equipment_id', sa.Uuid(), nullable=True),
    sa.Column('muscle_id', sa.Uuid(), nullable=True),
    sa.Column('video_url', sa.String(), nullable=True),
    sa.Column('video_provider', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['gym_equipments.id'], name=op.f('fk_exercises_equipment_id_gym_equipments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['muscle_id'], ['muscles.id'], name=op.f('fk_exercises_muscle_id_muscles'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exercises'))
    )
    op.create_index(op.f('ix_exercises_equipment_id'), 'exercises', ['equipment_id'], unique=False)
    op.create_index(op.f('ix_exercises_muscle_id'), 'exercises', ['muscle_id'], unique=False)
    op.create_table('user_ai_settings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('ai_provider_id', sa.Uuid(), nullable=False),
    sa.Column('ai_model_id', sa.Uuid(), nullable=False),
    sa.Column('api_key', sa.String(), nullable=False),
    sa.Column('api_url', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ai_model_id'], ['ai_models.id'], name=op.f('fk_user_ai_settings_ai_model_id_ai_models'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ai_provider_id'], ['ai_providers.id'], name=op.f('fk_user_ai_settings_ai_provider_id_ai_providers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_ai_settings_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_ai_settings'))
    )
    op.create_index(op.f('ix_user_ai_settings_ai_model_id'), 'user_ai_settings', ['ai_model_id'], unique=False)
    op.create_index(op.f('ix_user_ai_settings_ai_provider_id'), 'user_ai_settings', ['ai_provider_id'], unique=False)
    op.create_index(op.f('ix_user_ai_settings_user_id'), 'user_ai_settings', ['user_id'], unique=False)
    op.create_table('user_conditions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('condition_name', sa.String(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_conditions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_conditions'))
    )
    op.create_index(op.f('ix_user_conditions_user_id'), 'user_conditions', ['user_id'], unique=False)
    op.create_table('user_goal_answers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('question_id', sa.Uuid(), nullable=False),
    sa.Column('option_id', sa.Uuid(), nullable=True),
    sa.Column('answer_text', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['option_id'], ['goal_question_options.id'], name=op.f('fk_user_goal_answers_option_id_goal_question_options'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['question_id'], ['goal_questions.id'], name=op.f('fk_user_goal_answers_question_id_goal_questions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_goal_answers_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_goal_answers')),
    sa.UniqueConstraint('user_id', 'question_id', 'option_id', name='uq_user_goal_answers_user_question_option')
    )
    op.create_index(op.f('ix_user_goal_answers_option_id'), 'user_goal_answers', ['option_id'], unique=False)
    op.create_index(op.f('ix_user_goal_answers_question_id'), 'user_goal_answers', ['question_id'], unique=False)
    op.create_index(op.f('ix_user_goal_answers_user_id'), 'user_goal_answers', ['user_id'], unique=False)
    op.create_table('user_gyms',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('trainer_id', sa.Uuid(), nullable=True),
    sa.Column('gym_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['gym_id'], ['gyms.id'], name=op.f('fk_user_gyms_gym_id_gyms'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trainer_id'], ['users.id'], name=op.f('fk_user_gyms_trainer_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_gyms_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_gyms'))
    )
    op.create_index(op.f('ix_user_gyms_gym_id'), 'user_gyms', ['gym_id'], unique=False)
    op.create_index(op.f('ix_user_gyms_trainer_id'), 'user_gyms', ['trainer_id'], unique=False)
    op.create_index(op.f('ix_user_gyms_user_id'), 'user_gyms', ['user_id'], unique=False)
    op.create_table('exercise_equipment',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('exercise_id', sa.Uuid(), nullable=False),
    sa.Column('equipment_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['gym_equipments.id'], name=op.f('fk_exercise_equipment_equipment_id_gym_equipments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], name=op.f('fk_exercise_equipment_exercise_id_exercises'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exercise_equipment'))
    )
    op.create_index(op.f('ix_exercise_equipment_equipment_id'), 'exercise_equipment', ['equipment_id'], unique=False)
    op.create_index(op.f('ix_exercise_equipment_exercise_id'), 'exercise_equipment', ['exercise_id'], unique=False)
    op.create_table('workout_exercises',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('exercise_id', sa.Uuid(), nullable=False),
    sa.Column('sets', sa.Integer(), nullable=False),
    sa.Column('reps', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], name=op.f('fk_workout_exercises_exercise_id_exercises')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_workout_exercises_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workout_exercises'))
    )
    op.create_index(op.f('ix_workout_exercises_exercise_id'), 'workout_exercises', ['exercise_id'], unique=False)
    op.create_index(op.f('ix_workout_exercises_user_id'), 'workout_exercises', ['user_id'], unique=False)
    op.create_table('workout_exercise_details',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workout_exercise_id', sa.Uuid(), nullable=False),
    sa.Column('target_sets', sa.Integer(), nullable=False),
    sa.Column('actual_sets', sa.Integer(), nullable=True),
    sa.Column('target_reps', sa.Integer(), nullable=False),
    sa.Column('actual_reps', sa.Integer(), nullable=True),
    sa.Column('target_weight', sa.Float(), nullable=True),
    sa.Column('actual_weight', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workout_exercise_id'], ['workout_exercises.id'], name=op.f('fk_workout_exercise_details_workout_exercise_id_workout_exercises'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workout_exercise_details'))
    )
    op.create_index(op.f('ix_workout_exercise_details_workout_exercise_id'), 'workout_exercise_details', ['workout_exercise_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workout_exercise_details_workout_exercise_id'), table_name='workout_exercise_details')
    op.drop_table('workout_exercise_details')
    op.drop_index(op.f('ix_workout_exercises_user_id'), table_name='workout_exercises')
    op.drop_index(op.f('ix_workout_exercises_exercise_id'), table_name='workout_exercises')
    op.drop_table('workout_exercises')
    op.drop_index(op.f('ix_exercise_equipment_exercise_id'), table_name='exercise_equipment')
    op.drop_index(op.f('ix_exercise_equipment_equipment_id'), table_name='exercise_equipment')
    op.drop_table('exercise_equipment')
    op.drop_index(op.f('ix_user_gyms_user_id'), table_name='user_gyms')
    op.drop_index(op.f('ix_user_gyms_trainer_id'), table_name='user_gyms')
    op.drop_index(op.f('ix_user_gyms_gym_id'), table_name='user_gyms')
    op.drop_table('user_gyms')
    op.drop_index(op.f('ix_user_goal_answers_user_id'), table_name='user_goal_answers')
    op.drop_index(op.f('ix_user_goal_answers_question_id'), table_name='user_goal_answers')
    op.drop_index(op.f('ix_user_goal_answers_option_id'), table_name='user_goal_answers')
    op.drop_table('user_goal_answers')
    op.drop_index(op.f('ix_user_conditions_user_id'), table_name='user_conditions')
    op.drop_table('user_conditions')
    op.drop_index(op.f('ix_user_ai_settings_user_id'), table_name='user_ai_settings')
    op.drop_index(op.f('ix_user_ai_settings_ai_provider_id'), table_name='user_ai_settings')
    op.drop_index(op.f('ix_user_ai_settings_ai_model_id'), table_name='user_ai_settings')
    op.drop_table('user_ai_settings')
    op.drop_index(op.f('ix_exercises_muscle_id'), table_name='exercises')
    op.drop_index(op.f('ix_exercises_equipment_id'), table_name='exercises')
    op.drop_table('exercises')
    op.drop_index(op.f('ix_body_measurements_user_id'), table_name='body_measurements')
    op.drop_index(op.f('ix_body_measurements_trainer_id'), table_name='body_measurements')
    op.drop_index(op.f('ix_body_measurements_gym_id'), table_name='body_measurements')
    op.drop_table('body_measurements')
    op.drop_index(op.f('ix_users_role_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_gym_equipments_gym_id'), table_name='gym_equipments')
    op.drop_index(op.f('ix_gym_equipments_equipment_id'), table_name='gym_equipments')
    op.drop_table('gym_equipments')
    op.drop_index(op.f('ix_goal_question_options_question_id'), table_name='goal_question_options')
    op.drop_table('goal_question_options')
    op.drop_index(op.f('ix_ai_models_ai_provider_id'), table_name='ai_models')
    op.drop_table('ai_models')
    op.drop_table('roles')
    op.drop_table('muscles')
    op.drop_table('gyms')
    op.drop_table('goal_questions')
    op.drop_table('equipments')
    op.drop_table('ai_providers')
    # ### end Alembic commands ###
