"""fixed table

Revision ID: cc5eecdd1f18
Revises: 70ea0e85bba8
Create Date: 2026-07-09 13:08:48.027573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc5eecdd1f18'
down_revision: Union[str, Sequence[str], None] = '70ea0e85bba8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipments',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_gyms',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('trainer_id', sa.Uuid(), nullable=True),
    sa.Column('gym_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['gym_id'], ['gyms.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trainer_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_gyms_gym_id'), 'user_gyms', ['gym_id'], unique=False)
    op.create_index(op.f('ix_user_gyms_trainer_id'), 'user_gyms', ['trainer_id'], unique=False)
    op.create_index(op.f('ix_user_gyms_user_id'), 'user_gyms', ['user_id'], unique=False)
    question_type_enum = sa.Enum('CHECKBOX', 'RADIO', 'TEXT', name='question_type')
    question_type_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('goal_questions', sa.Column('question_type', question_type_enum, nullable=False, server_default='TEXT'))
    op.alter_column('goal_questions', 'question_type', server_default=None)
    op.drop_column('goal_questions', 'is_multiple_choice')
    op.add_column('gym_equipments', sa.Column('equipment_id', sa.Uuid(), nullable=False))
    op.create_index(op.f('ix_gym_equipments_equipment_id'), 'gym_equipments', ['equipment_id'], unique=False)
    op.create_foreign_key(None, 'gym_equipments', 'equipments', ['equipment_id'], ['id'], ondelete='CASCADE')
    op.drop_column('gym_equipments', 'name')
    op.drop_column('gym_equipments', 'description')
    op.drop_column('muscles', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('muscles', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('gym_equipments', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('gym_equipments', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'gym_equipments', type_='foreignkey')
    op.drop_index(op.f('ix_gym_equipments_equipment_id'), table_name='gym_equipments')
    op.drop_column('gym_equipments', 'equipment_id')
    op.add_column('goal_questions', sa.Column('is_multiple_choice', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('goal_questions', 'question_type')
    sa.Enum(name='question_type').drop(op.get_bind(), checkfirst=True)
    op.drop_index(op.f('ix_user_gyms_user_id'), table_name='user_gyms')
    op.drop_index(op.f('ix_user_gyms_trainer_id'), table_name='user_gyms')
    op.drop_index(op.f('ix_user_gyms_gym_id'), table_name='user_gyms')
    op.drop_table('user_gyms')
    op.drop_table('equipments')
    # ### end Alembic commands ###
